---
title: "04_Sens_Keep_extremeValues"
---
# Set Parameters and Load Packages
```{r}
library(readr)
library(haven)
library(dplyr)
library(ggplot2)
library(DataExplorer)
library(patchwork)
library(here)
source('DataInput_Distribution_Association.R')

custom_theme <- theme(
  panel.background = element_blank(),
  axis.ticks = element_blank(),
  axis.text = element_text(size = 10),
  axis.title = element_text(size = 12, face = "bold"),
  axis.line = element_line(size = 0.5),
  plot.title = element_text(size = 14, face = "bold", hjust = 0.5)
)

custom_theme2 <- theme(
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),  
    panel.background = element_blank(),  
    axis.ticks = element_blank(),  
    panel.border = element_rect(colour = "black", fill = NA, size = 1)
  )

step_algorithms = c('ADEPT', 'Oak', 'SDT', 'Stepcount', 'Verisense')
```

# 01.Visualize Step Counts
## Load data
```{r}
dat_vis = read_csv(here('00_Intermediate_output/03_Step_Cov_Imputed.csv'))
dat_vis$...1 = NULL
```

# Exclude extreme values
```{r}
result = dat_vis
ex.list = c()
for (var in step_algorithms){
  exetreme.lower = quantile(result[[var]], c(0.01, 0.99))[1]
  exetreme.upper = quantile(result[[var]], c(0.01, 0.99))[2]
  list.temp = result[result[[var]] > exetreme.upper | result[[var]] < exetreme.lower,]$subjectid
  ex.list = c(ex.list, list.temp)
}
result.noextreme = result[result$subjectid %in% setdiff(result$subjectid, unique(ex.list)),] # N=62 excluded
cat('The number of individuals who are excluded due to extreme values: ', dim(result)[1] - dim(result.noextreme)[1])
```

# 02.Distribution results
```{r}
dat.step = result.noextreme[,c(1,3:7)]/1000
step.distribution.subtitle(dat.step, '09.Sens.Exclude_extreme_By10')
step.distribution(dat.step, '09.Sens.Exclude_extreme_By10')
```

# 04.Output the datasets
```{r}
write.csv(result.ana, 
          '00_Intermediate_output/09_Step_Cov_V9_Exclude_extreme_By1.csv')
```

