---
title: "00_Analysis_pre"
---

# Set Parameters
```{r}
library(readr)
library(haven)
library(dplyr)
library(ggplot2)
library(DataExplorer)
library(patchwork)
library(robustbase) # for Adaptive Trimmed Mean Estimator
source('01_Functions_Base.R')
source('DataInput_Distribution_Association.R')

custom_theme <- theme(
  panel.background = element_blank(),
  axis.ticks = element_blank(),
  axis.text = element_text(size = 10),
  axis.title = element_text(size = 12, face = "bold"),
  axis.line = element_line(size = 0.5),
  plot.title = element_text(size = 14, face = "bold", hjust = 0.5)
)

custom_theme2 <- theme(
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),  
    panel.background = element_blank(),  
    axis.ticks = element_blank(),  
    panel.border = element_rect(colour = "black", fill = NA, size = 1)
  )

step_algorithms = c('ADEPT', 'Oak', 'SDT', 'Stepcount', 'Verisense')
```

# 01.Distribution results
## Load data
```{r}
dat_vis = read_csv('00_Intermediate_output/09_Step_Cov_WithoutSmokingImpute.csv')
dat_vis$...1 = NULL

dat_vis = dat_vis |> filter(!is.na(Smoking))
```

## Exclude extreme values
by Adaptive Trimmed Mean Estimator
```{r}
result = dat_vis
ex.list = c()
for (var in step_algorithms){
  adjbox_result <- adjbox(result[[var]], id.n = Inf, plot = TRUE)
  list.temp = which(result[[var]]  %in%  adjbox_result$out)
  ex.list = c(ex.list, list.temp)
}
ex.list = result$subjectid[ex.list]

result.noextreme = result[result$subjectid %in% setdiff(result$subjectid, # N=1215
                                                        unique(ex.list)),] # N=37 Excluded
cat('The number of individuals who are excluded due to extreme values: ',
    dim(result)[1] - dim(result.noextreme)[1])
```

# 02.Distribution results
```{r, warning=FALSE}
dat.step = result.noextreme[,c(1,3:7)]
step.distribution.subtitle(dat.step, '09.Sens.ExcludeSmoking_Association')
step.distribution(dat.step, '09.Sens.ExcludeSmoking_Association')
```

### Metabolic outcome
```{r, warning=FALSE}
dat_cov = result.noextreme
## Diabetes, CES.D, cogstatus
# dat_cov_V9 = dat_vis = read_csv('00_Intermediate_output/09_Step_Cov_WithoutSmokingImpute.csv') |>
#   dplyr::select(-`...1`) |>
#   dplyr::mutate(subjectid = sub('[A-Z]', '', subjectid))
# num = which(colnames(dat_cov_V9) %in% c('cogstatus'))
# dat_cov = merge(dat_cov, dat_cov_V9[,c(1,num)], 'subjectid')

dat_bio = read_dta('WIT_STEP/Met_Outcome.dta') |>
  dplyr::mutate(subjectid = sub('[A-Z]', '', subjectid))
dat_bio = dat_bio[dat_bio$visit == 'V9',c(1,3,5,7,9)]

## TG, TC, HDL-C, LDL-C
dat_cov = merge(dat_cov, dat_bio, by = 'subjectid', all.x = TRUE)

## FAT(%), FAT MASS(Kg)
dat_FAT = read_dta('WIT_STEP/FAT_Outcome.dta') |>
  dplyr::mutate(subjectid = sub('[A-Z]', '', subjectid))
dat_cov = merge(dat_cov, dat_FAT, by = 'subjectid', all.x = TRUE)
```

### Cardiovascular diseases
#### HF, MI, stroke
```{r}
dat_CVD = read_dta('/Users/gsn/Library/CloudStorage/OneDrive-JohnsHopkins/【JHU】Aging-RA/[ENGAGE]Cog_PA/EBA_Cog_PA/Derived_Data/CVD_all.dta') |>
  dplyr::mutate(subjectid = sub('[A-Z]', '', subjectid))

temp = merge(dat_cov, dat_CVD, 'subjectid', all.x = TRUE)
## Generate HF records
list_HF = temp |>
  mutate(time_label = HF_date <= exam_dat,
         HF_label = ifelse(HF == 1 & time_label, 1,0),
         HF = HF_label) |>
  select(-HF_label, -time_label, -HF_date)
list_HF$HF = ifelse(is.na(list_HF$HF), 0,list_HF$HF)

## Generate MI records
list_MI = temp |>
  mutate(time_label = MI_date <= exam_dat,
         MI_label = ifelse(MI == 1 & time_label, 1,0),
         MI = MI_label) |>
  select(-MI_label, -time_label, -MI_date) # The list of individuals who have HF before V5.
list_MI$MI = ifelse(is.na(list_MI$MI), 0,list_MI$MI)

## Generate Stroke records
list_stroke = temp |>
  mutate(time_label = stroke_date <= exam_dat,
         stroke_label = ifelse(stroke == 1 & time_label, 1,0),
         stroke = stroke_label) |>
  select(-stroke_label, -time_label, -stroke_date) # The list of individuals who have HF before V5.
list_stroke$stroke = ifelse(is.na(list_stroke$stroke), 0,list_stroke$stroke)

sum(!dat_cov$subjectid == list_HF$subjectid)
sum(!dat_cov$subjectid == list_MI$subjectid)
sum(!dat_cov$subjectid == list_stroke$subjectid)

dat_cov$HF = list_HF$HF
dat_cov$MI = list_MI$MI
dat_cov$Stroke = list_stroke$stroke
```

#### SBP, DBP, cfPWV, Hypertension, frality
```{r}
dat = read_dta('WIT_STEP/SBP_DBP_Outcome.dta') |>
  dplyr::mutate(subjectid = sub('[A-Z]', '', subjectid))
colnames(dat)[4:5] = c('Frailty_A', 'Frailty_B')
dat_cov = merge(dat_cov, dat, by = 'subjectid')

dat.pwv = read_dta('WIT_STEP/cf_pwv_Outcome.dta') |>
  dplyr::mutate(subjectid = sub('[A-Z]', '', subjectid)); colnames(dat.pwv)[2] = 'cfPWV'
dat_cov = merge(dat_cov, dat.pwv, by = 'subjectid', all.x = TRUE)
```

### Others
#### falls, fear of falling, frailty
```{r}
dat.fall = read_dta('WIT_STEP/FALL_Outcome.dta') |> select(-year) |>
  dplyr::mutate(subjectid = sub('[A-Z]', '', subjectid))
# table(dat.fall$FALL)
dat.fall = dat.fall |> mutate(FALL = case_when(FALL == 'A'~ 1,
                          FALL == 'B'~ 0,
                          FALL == 'C'~ NA))
dat.fall = dat.fall |>
  group_by(subjectid) |>
  summarise(FALL = sum(FALL))
dat_cov = merge(dat_cov, dat.fall, by = 'subjectid', all.x = TRUE)
```


#### Cognition
```{r}
dat.cog = read_dta('/Users/gsn/Library/CloudStorage/OneDrive-JohnsHopkins/【JHU】Aging-RA/[ENGAGE]Cog_PA/EBA_Cog_PA/Derived_Data/gen_Cog_all_derive.dta') |>
  dplyr::mutate(subjectid = sub('[A-Z]', '', subjectid))
dat.cog = dat.cog[dat.cog$visit == 9,]
dat.cog <- dat.cog %>%
  group_by(subjectid) %>% 
  filter(n() == 1 | vtype == "V9NCS") %>%  # Only samples with a unique subjectid or vtype of V9NCS are retained
  ungroup() 

dat_cov = merge(dat_cov, dat.cog, by = 'subjectid', all.x = TRUE)

write_csv(dat_cov, 'Results/09.Sens.ExcludeSmoking_Association/03_Step_Cov_Out.csv')
```


# 03.Association results
```{r, warning=FALSE}
num = which(colnames(dat_cov) %in% step_algorithms)

dat_cov.per = dat_cov; dat_cov.per[, num] = dat_cov.per[, num]/1000
association.result(dat_cov.per, '09.Sens.ExcludeSmoking_Association/')

dat_cov.scale = dat_cov; dat_cov.scale[, num] = scale(dat_cov.scale[,num])
association.result(dat_cov.scale, '09.Sens.ExcludeSmoking_Association/scaled/')
```

